In [1]:
import torch
a = torch.Tensor([[2,3],[4,5],[6,7]])
print('a is : {}'.format(a))
print('a size is :{}'.format(a.size()))

a is : tensor([[ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]])
a size is :torch.Size([3, 2])


In [2]:
b = torch.LongTensor([[2,3],[4,5],[6,7]])
print('b is :{}'.format(b))

b is :tensor([[ 2,  3],
        [ 4,  5],
        [ 6,  7]])


In [3]:
c = torch.zeros((3,2))

In [4]:
d = torch.randn((3,2))
print('c is {}\n d is {}'.format(c,d))

c is tensor([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])
 d is tensor([[-1.0456, -0.3933],
        [-0.6620, -0.1530],
        [ 0.3555, -0.6970]])


#### change Tensor to numpy

In [5]:
numpy_b = b.numpy()
print('conver to numpy is \n{}'.format(numpy_b))

conver to numpy is 
[[2 3]
 [4 5]
 [6 7]]


In [7]:
import numpy as np
e = np.array([[2,3],[4,5]])
torch_e = torch.from_numpy(e)
print('from numpy to torch.Tensor is {}'.format(torch_e))

from numpy to torch.Tensor is tensor([[ 2,  3],
        [ 4,  5]])


### Variable

In [8]:
from torch.autograd import Variable
x = Variable(torch.Tensor([1]), requires_grad = True)
w = Variable(torch.Tensor([2]), requires_grad = True)
b = Variable(torch.Tensor([3]), requires_grad = True)

y = w * x + b

y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

tensor([ 2.])
tensor([ 1.])
tensor([ 1.])
